### ISSUE TITLE
Orion-ld crashes several times during the start of the example

### ISSUE THREAD

**Issue by baston888** [FIWARE/tutorials.Subscriptions#17]
Dear colleagues, when executing the "sudo ./service orion legacy" command, orion-ld serially exits with code 1. Obviously, the health check of the application is triggered. This can be understood from the following log.
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/86f7cc0a-03f4-4852-9bdf-db0266327f46)
 Orion-ld must be restarted with "sudo docker start" many times before it returns a 200 code. 
![image](https://github.com/FIWARE/tutorials.Subscriptions/assets/72969990/1feaa6e8-a442-45fb-9080-fab548ce9f14)

**Comment by jason-fox** [comment]
This is probably a bug within Orion-LD itself - can you supply more details? I am unable t observe this fault when I run with the latest stable release as shown.


```yaml
orion:
    labels:
      org.fiware: 'tutorial'
    image: quay.io/fiware/orion-ld:1.4.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - 1026:1026
    command: -dbhost mongo-db -logLevel DEBUG -forwarding  -experimental
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
```
